#' Simulated Drought-Rewatering Dataset for rehydra
#'
#' A small simulated ecophysiology dataset with two genotypes (`Sensitive` and
#' `Tolerant`) under `Control` and `Drought` treatments across two complete
#' drought-rewatering cycles.
#'
#' @format A tibble with the following columns:
#' \describe{
#'   \item{plant_id}{Plant identifier.}
#'   \item{genotype}{Genotype level (`Sensitive`, `Tolerant`).}
#'   \item{time_days}{Time in days from 0 to 40.}
#'   \item{treatment}{Treatment level (`Control`, `Drought`).}
#'   \item{replicate}{Replicate identifier.}
#'   \item{cycle}{Cycle index (`1`, `2`).}
#'   \item{phase}{Cycle phase (`PreDrought`, `Drought`, `Rewatering`, `PostDrought`).}
#'   \item{water_potential}{Leaf water potential (MPa, simulated).}
#'   \item{stomatal_conductance}{Stomatal conductance (mol m-2 s-1, simulated).}
#' }
#'
#' @details
#' The `Tolerant` genotype has lower cycle-2 drought damage and stronger
#' recovery, while `Sensitive` shows stronger decline and weaker memory.
#' A small number of values are set to `NA` to support validation tests.
#'
#' @references
#' Lloret et al. (2011) <doi:10.1111/j.1600-0706.2011.19372.x>;
#' Xu et al. (2010) <doi:10.4161/psb.5.6.11398>;
#' Ribeiro et al. (2021) <doi:10.1016/j.jplph.2021.153397>.
#'
#' @source Simulated dataset generated by `data-raw/rehydra_data.R`.
"rehydra_data"
